"""general_waste_detection

Revision ID: 2aee2faec16c
Revises: '002_detection_failure_and_risk'
Create Date: 2026-08-08 18:38:30.901919

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '2aee2faec16c'
down_revision: Union[str, None] = '002_detection_failure_and_risk'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_items', sa.Column('class_name', sa.String(length=128), server_default='unknown', nullable=False))
    op.add_column('detection_items', sa.Column('waste_group', sa.String(length=64), server_default='unknown', nullable=False))
    op.drop_column('detection_items', 'waste_type')
    op.add_column('detections', sa.Column('annotated_image_url', sa.String(length=512), nullable=True))
    op.add_column('detections', sa.Column('processing_time_ms', sa.Float(), nullable=True))
    op.drop_constraint(op.f('risk_assessments_detection_id_key'), 'risk_assessments', type_='unique')
    op.drop_index(op.f('ix_risk_assessments_detection_id'), table_name='risk_assessments')
    op.create_index(op.f('ix_risk_assessments_detection_id'), 'risk_assessments', ['detection_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_detection_id'), table_name='risk_assessments')
    op.create_index(op.f('ix_risk_assessments_detection_id'), 'risk_assessments', ['detection_id'], unique=False)
    op.create_unique_constraint(op.f('risk_assessments_detection_id_key'), 'risk_assessments', ['detection_id'])
    op.drop_column('detections', 'processing_time_ms')
    op.drop_column('detections', 'annotated_image_url')
    op.add_column('detection_items', sa.Column('waste_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('detection_items', 'waste_group')
    op.drop_column('detection_items', 'class_name')
    # ### end Alembic commands ###
