"""Add location_confidence column

Revision ID: 6d878019c7c3
Revises: 'ae2e0de342a7'
Create Date: 2026-08-08 19:27:22.433029

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '6d878019c7c3'
down_revision: Union[str, None] = 'ae2e0de342a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('location_confidence', sa.Float(), nullable=True))
    op.alter_column('detections', 'location_source',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detections', 'location_source',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('detections', 'location_confidence')
    # ### end Alembic commands ###
