"""Add location_source and nullable lat_long

Revision ID: ae2e0de342a7
Revises: '2aee2faec16c'
Create Date: 2026-08-08 19:09:05.945725

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'ae2e0de342a7'
down_revision: Union[str, None] = '2aee2faec16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('location_source', sa.String(length=32), nullable=True))
    op.alter_column('detections', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('detections', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detections', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('detections', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('detections', 'location_source')
    # ### end Alembic commands ###
